# Generated by Django 6.0.6 on 2026-08-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AddMember', '0002_alter_addmember_member_id'),
        ('library', '0002_alter_books_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.books')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddMember.addmember')),
            ],
        ),
    ]
