# Generated by Django 6.0.6 on 2026-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
