# Generated by Django 6.0.6 on 2026-08-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_name', models.CharField(max_length=150)),
                ('member_id', models.CharField(max_length=50)),
                ('postion', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
