# Generated by Django 6.0.6 on 2026-08-05 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AddMember', '0002_alter_addmember_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddMember.addmember')),
            ],
        ),
    ]
