# Generated by Django 6.0.6 on 2026-08-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddMember', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmember',
            name='member_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
